---
- hosts: amazonos
  become: yes
  tasks:
  - name: i want to install webserver on ubuntu
    yum:
      name: httpd
      state: present

  - name: start the service
    service:
      name: httpd
      state: started

  - name: i want to copy index file into all nodes
    template:
      src: index.j2
      dest: /var/www/html/index.html